//! Deployment / provisioning subcommands shared by the client CLI.

use std::{fs, path::Path};

use anyhow::{Context, Result};
use octravpn_core::{address::Address, sig::KeyPair};
use rand::RngCore;

mod bugreport;
pub(crate) mod open_url;
pub(crate) mod serve;
pub(crate) mod slash;

pub(crate) use bugreport::run as bugreport;
pub(crate) use open_url::{open_url as run_open_url, OpenUrlArgs};
pub(crate) use serve::{run_funnel as funnel, run_serve as serve, Op as ServeOp};
pub(crate) use slash::{run as slash_evidence, submit as slash_submit, SlashCmd};

/// `octravpn init` — write a fresh config + wallet key into `dir`.
///
/// Layout:
///   <dir>/client.toml
///   <dir>/wallet.key      (32-byte hex; chmod 0600)
pub(crate) fn init(
    dir: &str,
    rpc_url: Option<&str>,
    program_addr: Option<&str>,
    force: bool,
) -> Result<()> {
    let dir_path = Path::new(dir);
    fs::create_dir_all(dir_path).with_context(|| format!("mkdir {dir}"))?;

    let config_path = dir_path.join("client.toml");
    let wallet_path = dir_path.join("wallet.key");

    if config_path.exists() && !force {
        anyhow::bail!(
            "{} already exists; pass --force to overwrite",
            config_path.display()
        );
    }
    if wallet_path.exists() && !force {
        anyhow::bail!(
            "{} already exists; pass --force to overwrite",
            wallet_path.display()
        );
    }

    let kp = KeyPair::generate();
    let secret_hex = hex::encode(kp.secret_bytes());
    let addr = Address::from_pubkey(&kp.public.0);

    write_secret_0600(&wallet_path, &secret_hex)?;
    let cfg = format!(
        r#"# Generated by `octravpn init`.

[chain]
rpc_url      = "{rpc}"
program_addr = "{prog}"

[wallet]
addr        = "{addr}"
secret_path = "{wallet}"
"#,
        rpc = rpc_url.unwrap_or("https://octra.network/rpc"),
        prog = program_addr.unwrap_or("octPROG_REPLACE_ME"),
        addr = addr.display(),
        wallet = wallet_path.display(),
    );
    fs::write(&config_path, cfg).with_context(|| format!("write {}", config_path.display()))?;

    println!("wrote {}", config_path.display());
    println!("wrote {}  (chmod 0600)", wallet_path.display());
    println!("wallet address: {}", addr.display());
    if program_addr.is_none() {
        println!();
        println!(
            "⚠  program_addr is a placeholder. Edit {} and replace",
            config_path.display()
        );
        println!("   `program_addr` with the deployed OctraVPN program address.");
    }
    Ok(())
}

/// `octravpn keygen` — generate a fresh wallet secret and write to `out`.
pub(crate) fn keygen(out: &str) -> Result<()> {
    let path = Path::new(out);
    if path.exists() {
        anyhow::bail!("{} already exists; refusing to overwrite", path.display());
    }
    let kp = KeyPair::generate();
    let secret_hex = hex::encode(kp.secret_bytes());
    let addr = Address::from_pubkey(&kp.public.0);
    write_secret_0600(path, &secret_hex)?;
    println!("wrote {}", path.display());
    println!("address: {}", addr.display());
    Ok(())
}

/// `octravpn doctor` — run preflight checks. On failure, prints which
/// checks failed and exits non-zero (process::exit, not Err). Returns
/// `Result` only so the call site keeps consistent error types with
/// the other subcommands.
#[allow(clippy::unnecessary_wraps)]
pub(crate) fn doctor(config_path: &str) -> Result<()> {
    let mut failures = Vec::new();
    let mut ok = |label: &str, result: Result<()>| match result {
        Ok(()) => println!("[ ok ] {label}"),
        Err(e) => {
            println!("[fail] {label}: {e}");
            failures.push(label.to_string());
        }
    };

    // 1. Config file readable.
    ok(
        "config file readable",
        std::fs::read_to_string(config_path)
            .map(|_| ())
            .with_context(|| format!("read {config_path}")),
    );

    // 2. Wallet key 32 bytes (raw or hex).
    let cfg_loaded = std::fs::read_to_string(config_path).ok();
    if let Some(cfg) = cfg_loaded {
        // Extract `secret_path = "..."` heuristically.
        if let Some(path) = extract_toml_string(&cfg, "secret_path") {
            ok(
                "wallet secret loadable",
                octravpn_core::util::read_secret_32(&path)
                    .map(|_| ())
                    .with_context(|| format!("read wallet secret {path}")),
            );
        }
    }

    // 3. TUN preflight.
    ok("TUN device subsystem present", octravpn_tun::doctor());

    // 4. Platform-specific quick checks.
    #[cfg(target_os = "linux")]
    {
        ok(
            "kernel supports user namespaces (optional)",
            check_path_exists("/proc/self/ns/net"),
        );
    }
    #[cfg(target_os = "macos")]
    {
        ok(
            "macOS version sufficient",
            check_command("sw_vers", &["-productVersion"]),
        );
    }
    #[cfg(target_os = "windows")]
    {
        ok(
            "wintun driver discoverable",
            check_command("powershell", &["-c", "Get-Command wintun.dll"]),
        );
    }

    println!();
    if failures.is_empty() {
        println!("All checks passed.");
        Ok(())
    } else {
        println!(
            "{} check(s) failed: {}",
            failures.len(),
            failures.join(", ")
        );
        std::process::exit(1);
    }
}

fn write_secret_0600(path: &Path, contents: &str) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = fs::Permissions::from_mode(0o600);
        fs::set_permissions(path, perms)
            .with_context(|| format!("chmod 0600 {}", path.display()))?;
    }
    Ok(())
}

fn extract_toml_string(text: &str, key: &str) -> Option<String> {
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with(&format!("{key} =")) || line.starts_with(&format!("{key}=")) {
            if let Some(start) = line.find('"') {
                if let Some(end) = line[start + 1..].find('"') {
                    return Some(line[start + 1..start + 1 + end].to_string());
                }
            }
        }
    }
    None
}

#[cfg(target_os = "linux")]
fn check_path_exists(p: &str) -> Result<()> {
    if Path::new(p).exists() {
        Ok(())
    } else {
        Err(anyhow::anyhow!("{p} not found"))
    }
}

#[cfg(any(target_os = "macos", target_os = "windows"))]
fn check_command(cmd: &str, args: &[&str]) -> Result<()> {
    use std::process::Command;
    let s = Command::new(cmd)
        .args(args)
        .output()
        .with_context(|| format!("spawn {cmd}"))?;
    if s.status.success() {
        Ok(())
    } else {
        Err(anyhow::anyhow!(
            "{cmd} {} exited {}: {}",
            args.join(" "),
            s.status,
            String::from_utf8_lossy(&s.stderr)
        ))
    }
}

/// Unused helpers depending on cfg. Kept here to make conditional
/// compilation cleaner.
#[cfg(target_os = "windows")]
fn _windows_marker() {}

// Helper so rand is referenced (for `KeyPair::generate` ergonomics in
// future provisioning paths).
#[allow(dead_code)]
fn fresh_secret_bytes() -> [u8; 32] {
    let mut buf = [0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut buf);
    buf
}
