#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop octravpn-node >/dev/null 2>&1 || true
  systemctl disable octravpn-node >/dev/null 2>&1 || true
fi

#DEBHELPER#
exit 0
