//! `forge bind` — generate typed Rust stubs from a compiled ABI.
//!
//! Output shape (per program):
//!
//! ```ignore
//! pub mod octravpn {
//!     use octravpn_core::address::Address;
//!     use serde_json::{json, Value};
//!     pub struct Contract { pub addr: String }
//!     impl Contract {
//!         pub fn call_register_validator(
//!             &self,
//!             endpoint: &str,
//!             wg_pubkey: &str,
//!             // ...
//!         ) -> Value { ... }
//!         pub fn view_get_validator(&self, addr: &str) -> Value { ... }
//!     }
//! }
//! ```
//!
//! These builders produce `serde_json::Value` envelopes ready for
//! `octravpn_core::tx::sign_call` (call methods) or `rpc_client::call`
//! with `contract_call` (view methods). They're deliberately minimal so
//! the generated file compiles against just `octravpn-core` +
//! `serde_json` with no further imports.

use std::path::PathBuf;

use anyhow::{anyhow, Context, Result};
use clap::Args;
use serde_json::Value;

#[derive(Args, Debug)]
pub struct BindArgs {
    /// Path to a compiled ABI JSON (`out/<Name>.abi` or `.json`).
    pub abi: PathBuf,
    /// Output directory.
    #[arg(long, default_value = "bindings")]
    pub out: PathBuf,
    /// Module name (default: derived from ABI file stem, snake-cased).
    #[arg(long)]
    pub module: Option<String>,
}

pub fn run(args: &BindArgs) -> Result<()> {
    let raw = std::fs::read_to_string(&args.abi)
        .with_context(|| format!("read {}", args.abi.display()))?;
    let v: Value = serde_json::from_str(&raw)?;
    let abi: Vec<Value> = if let Some(a) = v.as_array() {
        a.clone()
    } else if let Some(a) = v.get("abi").and_then(|x| x.as_array()) {
        a.clone()
    } else {
        return Err(anyhow!("ABI file must be an array or `{{abi: []}}`"));
    };
    let program_name = v
        .get("name")
        .and_then(|x| x.as_str())
        .map(str::to_string)
        .or_else(|| {
            args.abi
                .file_stem()
                .and_then(|s| s.to_str())
                .map(str::to_string)
        })
        .unwrap_or_else(|| "Program".to_string());
    let module = args
        .module
        .clone()
        .unwrap_or_else(|| to_snake_case(&program_name));
    let body = render(&program_name, &module, &abi);
    let path = args.out.join(format!("{module}.rs"));
    crate::io::write_to(&path, &body)?;
    println!("wrote {}", path.display());
    Ok(())
}

fn render(program: &str, module: &str, abi: &[Value]) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    let struct_name = pascal(module);
    let _ = write!(
        out,
        "// Generated by `octra forge bind`. Do not edit by hand.\n\
         // Program: {program}\n\
         #![allow(dead_code, unused_variables, clippy::needless_pass_by_value)]\n\
         \n\
         use serde_json::{{json, Value}};\n\
         \n\
         pub struct {struct_name} {{\n\
         \x20\x20\x20\x20pub addr: String,\n\
         \x20\x20\x20\x20pub from: String,\n\
         }}\n\
         \n\
         impl {struct_name} {{\n\
         \x20\x20\x20\x20pub fn new(addr: impl Into<String>, from: impl Into<String>) -> Self {{\n\
         \x20\x20\x20\x20\x20\x20\x20\x20Self {{ addr: addr.into(), from: from.into() }}\n\
         \x20\x20\x20\x20}}\n\
         \n",
    );
    for item in abi {
        let kind = item.get("kind").and_then(|x| x.as_str()).unwrap_or("call");
        if kind == "event" {
            continue;
        }
        let name = match item.get("name").and_then(|x| x.as_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };
        let inputs: Vec<(String, String)> = item
            .get("inputs")
            .and_then(|x| x.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|inp| {
                        let n = inp.get("name").and_then(|x| x.as_str()).map(str::to_string)?;
                        let t = inp.get("type").and_then(|x| x.as_str()).map(str::to_string)?;
                        Some((n, t))
                    })
                    .collect()
            })
            .unwrap_or_default();
        let fn_name = if kind == "view" {
            format!("view_{name}")
        } else {
            format!("call_{name}")
        };
        let arg_list: Vec<String> = inputs
            .iter()
            .map(|(n, t)| format!("{}: {}", sanitize_ident(n), aml_type_to_rust(t)))
            .collect();
        let arg_decl = arg_list.join(", ");
        let arg_json = inputs
            .iter()
            .map(|(n, t)| pack_arg(n, t))
            .collect::<Vec<_>>()
            .join(", ");
        if kind == "view" {
            let _ = write!(
                out,
                "\x20\x20\x20\x20pub fn {fn_name}(&self, {arg_decl}) -> Value {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20json!([self.addr.clone(), \"{name}\", [ {arg_json} ]])\n\
                 \x20\x20\x20\x20}}\n\n",
            );
        } else {
            let _ = write!(
                out,
                "\x20\x20\x20\x20pub fn {fn_name}(&self, {arg_decl}) -> Value {{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20json!({{\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"kind\": \"contract_call\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"from\": self.from.clone(),\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"to\": self.addr.clone(),\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"method\": \"{name}\",\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"params\": [ {arg_json} ],\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"value\": 0u64,\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"fee\": 10u64,\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\"nonce\": 0u64,\n\
                 \x20\x20\x20\x20\x20\x20\x20\x20}})\n\
                 \x20\x20\x20\x20}}\n\n",
            );
        }
    }
    out.push_str("}\n");
    out
}

fn aml_type_to_rust(t: &str) -> String {
    // Conservative mapping. Aliases stay so users see what the ABI
    // promised; widening to `Value` keeps the binding compiling even
    // when the AML grammar introduces new types.
    match t {
        "int" => "i64".into(),
        "uint" | "u64" => "u64".into(),
        "bool" => "bool".into(),
        "bytes" | "string" | "address" => "&str".into(),
        _ => "Value".into(),
    }
}

fn pack_arg(name: &str, ty: &str) -> String {
    let ident = sanitize_ident(name);
    match ty {
        "int" | "uint" | "u64" | "bool" | "bytes" | "string" | "address" => {
            format!("json!({ident})")
        }
        _ => format!("{ident}.clone()"),
    }
}

fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 && !out.ends_with('_') {
                out.push('_');
            }
            for low in ch.to_lowercase() {
                out.push(low);
            }
        } else {
            out.push(ch);
        }
    }
    out
}

fn pascal(snake: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for ch in snake.chars() {
        if ch == '_' {
            up = true;
            continue;
        }
        if up {
            for c in ch.to_uppercase() {
                out.push(c);
            }
            up = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn sanitize_ident(s: &str) -> String {
    const RUST_KW: &[&str] = &[
        "type", "match", "move", "mut", "ref", "self", "Self", "impl", "trait",
        "where", "while", "for", "let", "const", "fn", "if", "else", "loop", "in",
        "pub", "mod", "use", "as",
    ];
    let cleaned: String = s
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    let starts_digit = cleaned.chars().next().is_some_and(|c| c.is_ascii_digit());
    let base = if starts_digit { format!("_{cleaned}") } else { cleaned };
    if RUST_KW.contains(&base.as_str()) {
        format!("r#{base}")
    } else {
        base
    }
}
