#!/usr/bin/env bash
# replay-line.sh — `say` helper for fast-cut demo tapes.
#
# Usage in a tape (vhs):
#   Type 'source demo/lib/replay-line.sh'
#   Enter
#   Type 'say "bash demo/lib/devnet-bringup.sh" demo/captures/master-tour/01.txt'
#   Enter
#
# `say` prints a fake shell prompt + the command verbatim, then cats
# the pre-recorded capture file. Renders deterministically in <100ms
# instead of waiting on a real docker exec, which keeps tapes inside
# the 30s ceiling without losing the typed-command-then-output look.
#
# Captures are regenerated by `demo/lib/capture-master-tour.sh` (and
# friends) against the live harness — so they stay faithful even
# though the tape never reaches the live harness at render time.

# shellcheck disable=SC2034
say() {
    local cmd="$1"
    local capture="$2"
    printf '$ %s\n' "$cmd"
    if [[ -n "${capture:-}" && -f "${capture}" ]]; then
        cat "${capture}"
    fi
}
